NFT Section added in README.md
alexandresanlim/Badges4-README.md-Profile pull request #518
Opened 2023-01-07 13:55 UTC by jyotirmoydotdev

2023-01-09 01:52 UTC, mrhrifat requested changes
If you think to create a `group` of badge, it shortcut option should at top `Menu` section. Please make a change to `NFT` **second** badge `logoColor` to white.

2023-01-10 05:31 UTC, jyotirmoydotdev commented
Changes done ✅

2023-01-10 05:32 UTC, jyotirmoydotdev commented on README.md
> +  - [🏞️ NFT 🔝](#️-nft-)
Shortcut to NFT section

2023-01-10 09:51 UTC, mrhrifat requested changes
Please don't make any change to `Quicke Navigate` of section `Menu`. If you've any idea than share it first by creating `Issue`. Revert & just add `NFT`.

2023-01-10 17:46 UTC, closed without merging