Add Immich
alexandresanlim/Badges4-README.md-Profile pull request #740
Opened 2024-12-12 20:44 UTC by coltenkrauter

[Immich](https://immich.app/) is the ultimate self-hosted solution for managing photos and videos locally. Designed for privacy-focused users, Immich allows you to upload, organize, and view your media effortlessly, all while keeping full control over your data. Its modern interface, API flexibility, and advanced features make it one of the best tools in the home lab ecosystem. Perfect for users looking to build a personal media hub.

Also, note that I added a new section... I didn’t find a section that fit `Immich`, so I added `HomeLab`. Home labs are growing fast, giving people more control over their data and infrastructure. This new section highlights tools for self-hosting and on-prem solutions, starting with Immich, a top-tier local media hosting platform.

Also, note, I am not an Immich source-code maintainer, so they may come along later and adjust this badge.

## Preview

![image](https://img.shields.io/badge/immich-black?logo=immich&logoColor=fa2921&style=flat-square&labelColor=ffb400&color=ffb400)

2024-12-12 21:16 UTC, coltenkrauter commented
Shared with Immich folks here: https://github.com/immich-app/immich/discussions/14678#discussioncomment-11549380

2024-12-17 05:33 UTC, mrhrifat requested changes
As our all badge are styled with `style=for-the-badge`[^1] type, Please modify from `flat-square` to that.

[^1]: [Team Speak](https://img.shields.io/badge/TeamSpeak-2580C3?style=for-the-badge&logo=teamspeak&logoColor=white)

2024-12-17 18:10 UTC, coltenkrauter commented on README.md
> +| <img src="https://img.shields.io/badge/immich-black?logo=immich&logoColor=fa2921&style=flat-square&labelColor=ffb400&color=ffb400" />                 | `https://img.shields.io/badge/immich-black?lo
```suggestion
| <img src="https://img.shields.io/badge/immich-black?logo=immich&logoColor=fa2921&style=for-the-badge&labelColor=ffb400&color=ffb400" />                 | `https://img.shields.io/badge/immich-black?logo=immich&logoColor=fa2921&style=for-the-badge&labelColor=ffb400&color=ffb400`                 |
```

2024-12-18 09:49 UTC, mrhrifat approved these changes
Thanks for your contribution.

2024-12-18 09:50 UTC, merged